name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 배포

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Jekyll을 위한 Ruby 버전

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site